ph5/config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  
  # Set the root url
  root :to => 'home#home'
  
end

ph5/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  
  def index
    @active_addresses = Address.active.by_customer.by_recipient.paginate(:page => params[:page]).per_page(10)
    @inactive_addresses = Address.inactive.by_customer.by_recipient.paginate(:page => params[:page]).per_page(10)
  end

  def show
  end

  def new
    @address = Address.new
  end

  def edit
  end

  def create
    @address = Address.new(address_params)
    
    if @address.save
      redirect_to customer_path(@address.customer), notice: "The address was added to #{@address.customer.proper_name}."
    else
      render action: 'new'
    end
  end

  def update
    if @address.update(address_params)
      redirect_to addresses_path, notice: "The address was revised in the system."
    else
      render action: 'edit'
    end
  end


  private
  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:customer_id, :recipient, :street_1, :street_2, :city, :state, :zip, :active, :is_billing, :customer_id)
  end

end

ph5/app/views/addresses/_active_addresses.html.erb
<%= render partial: "address_list", locals: {addresses: @active_addresses, state: 'active'} %>

ph5/app/views/addresses/_address_details.html.erb
<h3>Address Information</h3>

<p>
  <b>Recipient</b>: <%= @address.recipient %>
</p>

<p>
  <b>Address</b>: <br />
  <%= render :partial => "partials/address_info", locals: {address: @address} %>
</p>

<p>
  <b>Billing</b>: <%= @address.is_billing ? 'Yes' : 'No' %>
</p>

<p>
  <b>Active</b>: <%= @address.active ? 'Yes' : 'No' %>
</p>

ph5/app/views/addresses/_address_list.html.erb
<% if addresses.empty? %>
  <p><em>There are no <%= state %> addresses at this time.</em></p>
<% else %>
<h2><%= state.capitalize %> Addresses</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th width="225">Customer</th>
      <th width="225">Recipient</th>
      <th width="350">Address</th>
      <th width="75">Billing?</th>
      <th width="75">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% addresses.each do |address| %>
      <tr>
        <td><%= link_to address.customer.proper_name, customer_path(address.customer) %></td>
        <td><%= address.recipient %></td>
        <td>
          <%= render :partial => "partials/address_info", locals: {address: address} %>
        </td>
        <td align="center"><%= address.is_billing ? "Yes" : "No" %></td>      
        <td>
          <%= link_to(edit_address_path(address), class: 'button tiny radius warning') do %>
            &nbsp;Edit&nbsp;
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate addresses, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>  
<% end %>
<p>&nbsp;</p>

ph5/app/views/addresses/_fields.html.erb
    <%= f.input :customer_id, collection: Customer.active.alphabetical, include_blank: true, input_html: {class: "avg"} %>

    <%= f.input :recipient, input_html: {class: "avg"} %>
    <%= f.input :street_1, input_html: {class: "avg"} %>
    <%= f.input :street_2, input_html: {class: "avg"} %>
    <%= f.input :city, input_html: {class: "avg"} %>
    <%= f.input :state, collection: Address::STATES_LIST, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :zip, input_html: {class: "avg"} %>
    <%= f.input :is_billing, label: 'Billing? ' %>
    <%= f.input :active %>

ph5/app/views/addresses/_form.html.erb
<%= simple_form_for @address, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Address</legend>

    <%= f.input :customer_id, collection: Customer.active.alphabetical, include_blank: true, input_html: {class: "avg"} %>

    <%= f.input :recipient, input_html: {class: "avg"} %>
    <%= f.input :street_1, input_html: {class: "avg"} %>
    <%= f.input :street_2, input_html: {class: "avg"} %>
    <%= f.input :city, input_html: {class: "avg"} %>
    <%= f.input :state, collection: Address::STATES_LIST, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :zip, input_html: {class: "avg"} %>
    <%= f.input :is_billing, label: 'Billing? ' %>
    <%= f.input :active %>


    <div class="form-actions">
      <%= f.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', addresses_path, :class => 'button alert radius' %>
    </div>
  </fieldset>
<% end %>

ph5/app/views/addresses/_inactive_addresses.html.erb
<%= render partial: "address_list", locals: {addresses: @inactive_addresses, state: 'inactive'} %>

ph5/app/views/addresses/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @address, 
                                                        type_of_form: "Edit Address",
                                                        fields: "fields"} %>

ph5/app/views/addresses/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "address", 
                                                         primary: "active_addresses", 
                                                         secondary: "inactive_addresses", 
                                                         sidebar: nil} %>

ph5/app/views/addresses/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @address, 
                                                        type_of_form: "New Address",
                                                        fields: "fields"} %>

ph5/app/views/addresses/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <%= render :partial => "address_details" %>
  </div>
  <div class="small-5 columns">
    &nbsp;
  </div>
</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "address", object: @address}  %>